add Looper#step/resume for pause looper
akashic-games/headless-driver pull request #187
Opened 2020-10-02 10:53 UTC by kamakiri01

## このpull requestが解決する内容

Looper を一時的に停止/再開させるメソッド `pause` `resume` を追加します。

## 破壊的な変更を含んでいるか?

- なし

2020-10-02 22:33 UTC, xnv commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
> +	private looper: Looper;
一つである保証はないので、配列で全て保持して、止める時は全て止める必要があると思います。

2020-10-06 03:08 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
> +	private looper: Looper;
`Looper[]` に直します。

2020-10-08 03:23 UTC, xnv requested changes

2020-10-08 03:23 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +	private _running: boolean;
この変数必要でしょうか。参照箇所なさそうですし、 `_userStarted && _platformStarted` と常に同値ではありませんか。

2020-10-08 03:23 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +		return !!this._timerId;
- このメソッド、新規追加に見えますが、利用箇所ありますか？
- start() と強く対称性を感じる名前ですが、実態的には userStart() まで込みの動作をしているのが気になります。このメソッドが必要なら、 `isActualStarted()` とか、ただの start とは違うものへの問い合わせであることを名前で示唆したいです。
- 値は `_userStarted && _platformStarted` で代用できそうです。(これでも別に正しく動作しそうですが)

2020-10-08 03:23 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +				this._stop();
- 異常系なのでアレですが、フラグを落とさないと、ここにきた後二度と再 start() できなそうなのが気になります。ここにいるということは platformStarted も userStarted も立ってると思うので、前者を落とすのはどうでしょうか。
- しかし本当はここで止めない方が便利なような気も……？(コンテンツが完全に止まりそうなので)

2020-10-08 03:23 UTC, xnv commented on packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
> +	pauseLooper(): void {
imo: loopers をまとめて扱ってるとこは全体的に複数形 (`pauseLoopers()` とか) にしたいですね……。

2020-10-08 03:23 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +		this._userStarted = true;
フラグも `_debugStarted` に揃えちゃった方がわかりやすいような気がしますがどうでしょう。

2020-10-13 08:00 UTC, kamakiri01 commented on packages/headless-driver-runner/src/Looper.ts
> +		this._userStarted = true;
同意します。揃えます。

2020-10-13 08:00 UTC, kamakiri01 commented on packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
> +	pauseLooper(): void {
確かに名前は複数形にしたいです。直します。

2020-10-13 08:00 UTC, kamakiri01 commented on packages/headless-driver-runner/src/Looper.ts
> +				this._stop();
- `this._platformStarted = false;` を追加します。
- …が、 Looperの提供する挙動としてはどちらが正しいのかと言うと 🤔 ですね。外側がstartを呼び直せる実装を持つべき、という視点もありそうな…

2020-10-13 08:00 UTC, kamakiri01 commented on packages/headless-driver-runner/src/Looper.ts
> +		return !!this._timerId;
修正の初期に追加したものですが、利用しなくなっていました。削除します。

2020-10-13 08:00 UTC, kamakiri01 commented on packages/headless-driver-runner/src/Looper.ts
> +	private _running: boolean;
`_update()` で参照はしていて、例えば `start()` が呼ばれたとき、 `_userStarted && _platformStarted` はフラグが更新済みなので意味が変わると思います。
フラグを更新するタイミングを変えるべきでしょうか。

2020-10-16 01:55 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +	private _running: boolean;
いやすいませんボケてました。これは必要ですね。

2020-10-16 01:57 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +				this._stop();
どっちにしても looper が止まってることを検出しないと動かないですよねえ。

このタスクの趣旨からは外れると思いませんが、あんま考えてないので、TODOコメントで「例外発生時止めてしまうのがいいのか検討する」とか書いておきませんか。

2020-10-16 02:06 UTC, xnv approved these changes
コメント加えていますが approved.

2020-10-16 02:06 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +			this._fun(16);
これ 16 で大丈夫か気になります。(16 * 60 === 960 なので、60 回 (60FPS の 1000ms 秒分) 呼んでも  960ms しか進んでおらず、 2.4 フレ足りなくなりそう＝ debuStep() 呼び出したのに進まないフレームが 2.4 回発生しそう)

`Clock` は実数値でも動くように作ってあったはずなので、  `1000 / 60` を渡しておきませんか。

2020-10-20 09:00 UTC, kamakiri01 commented on packages/headless-driver-runner/src/Looper.ts
> +			this._fun(16);
直します。

2020-11-06 03:12 UTC, merged