feat: Add Runner#advance()
akashic-games/headless-driver pull request #199
Opened 2020-11-11 04:17 UTC by yu-ogi

## このPullRequestを解決する内容
* `Runner#advance()` を追加
  * 指定のミリ秒だけ Runner を進めます。
* #187 にて追加された処理を一部修正
  * **※ #187にテストが存在しなかったため、この修正によるエンバグ等については未確認です**
  * `Runner#step()` の処理を修正します
  * `Looper#debug...` を削除し、 `Looper#start()`, `Looper#stop()` に一元化します
* `Runner` のテストを追加
* CI によるテストを Github Actions に変更
* その他 deprecated な部分や typo の修正など

2020-11-11 04:18 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +	private fps: number | null = null;
1フレームの時間はゲームに依存するため、 `g.Game` を知っている `Runner` が fps を保持するようにします。

2020-11-11 04:18 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +		this.platform.advanceLoopers(Math.ceil(1000 / this.fps));
天井関数により、 Looper による処理が必ず実行されるようにします。

2020-11-11 04:20 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +			// NOTE: game-driver の内部実装により Looper 経由で一度に進める時間に制限がある。
[このあたりの処理](https://github.com/akashic-games/game-driver/blob/9deee866ddb5d16f2836d3e7c9c30eb0c0f753f1/src/ProfilerClock.ts#L32-L35) に該当するっぽく、Looper の実行を分割してます。

2020-11-11 04:22 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> -	 * game-driverがプレイを続行する状態になっているかどうか
依存の末端である headless-driver-runner が game-driver を知っているのは奇妙に思え、このあたりの処理をまるごと修正しています。

2020-11-11 04:23 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> -		this._stepDelta = 1000 / 60;
`1000 / 60` 固定の意味がよくわからず (fps = 60 前提?)、RunnerVx に持たせるようにしました。

2020-11-11 04:24 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> -	debugStart(): void {
このあたりの正常系動作がよくわからず混乱してしまったため、Looper は `start()`, `stop()`, `advance()` のみを持たせるように修正してしまいました。

2020-11-11 05:10 UTC, kamakiri01 approved these changes
✔️ 
serveに組み込んでstop/step操作が動作するかのスモークテストをお願いしたいです。

2020-11-11 05:54 UTC, yu-ogi commented
> serveに組み込んでstop/step操作が動作するかのスモークテストをお願いしたいです。

PullRequestのコメントにも明記しましたが、どのような動作が正解なのかがわからないので対応を見送らせてください。コンテンツの動作を含めたスモークテストについては [RunnerSpec.ts](https://github.com/akashic-games/headless-driver/blob/939310e5240664a819c16582c4af455247b20c2a/packages/headless-driver/src/__tests__/RunnerSpec.ts) で確認済みです。
(akashic-cli 側のビルドが成功することまでは確認できています。)

2020-11-12 08:19 UTC, xnv requested changes

2020-11-12 08:19 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +	 * Looper#start() から Looper#stop() の間に呼ばれなければならない。
不要な制限が増えていませんか。

どうにもイメージが伝わっていない気がするのですが、 `start()` と `debugStart()` はこのクラスにつけられた二つのスイッチのようなものになっていました。このクラスは **二つのスイッチを直列に接続した電気回路** のようなものです。両方オンの時にのみ実際の動作 (定期的に `_fun()` を呼ぶ) を行い、片方でもオフにされればただちにそれをやめる、それ以上でもそれ以下でもないクラスでした。

別の比喩を考えれば、これは **自動車学校の車のブレーキ** に似ています。自動車学校の車が進むのは、運転席 (`start()`, `stop()`) のブレーキが踏まれておらず、かつ助手席の教官の足元 (`debugStart()`, `debugStop()`) のブレーキも踏まれていない時です。運転手がアクセルを踏んでいるか (`start()` している) かいないかは、 助手席の教官の意思とは関係がありません。

現状このクラスには二つの利用者 (本来の利用者である game-driver と、それに対してデバッグ・テスト用途で特権的に介入するもの) がいるわけですから、このように二つのスイッチを持つものに擬えるのは不自然ではないと思います。

----

今、このクラスの仕様はそのような「直列回路」よりもはるかに難しいものになっていると思います。

上の比喩に従えば、「助手席の教官のブレーキは、運転手がアクセルを踏んでいる間しか踏めない」という制限が追加されているような状態に見えます。

----

イメージはともかくとしても実際問題、`debugStop()` する時 (たとえば serve でポーズボタンが押された時)、する側 (serve) は

- 「この `Looper` が `start()` されているかどうか」を意識せねばならなくなっており、
- にも関わらず `start()` されているか知る方法は恐らくなく、
- さらに `start()` されていなかった時にできることがない

ように見えます。現実にはこれが問題になるケースはあまりない (game-driver は暗黙的・能動的に Looper を制御していないので)(言い換えると "運転手" は言われるがままアクセル踏みっぱなしなので) ようには思えますが、どうにも概念的に奇妙に思えます。

2020-11-12 08:19 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> -	 * game-driverがプレイを続行する状態になっているかどうか
このコメントは修正されるべきだと思いますが、このコメントが本当に言いたかったことは、「`start()`, `stop()` という (本来の利用者向けの) I/F がどう使われてどういう状態にあるか」だと思います。実際問題、このフラグの扱いは game-driver について (当然ですが) 全く感知しておらず、単に `start()`, `stop()` で上げ下げされるだけです。

このクラスのメソッドの呼び出され具合をこのクラスが把握しているのはごく自然なことでしょう。改名やコメントの修正はあるべきに思えますが、それはこのフラグを消すという判断にはただちには繋がらないと思います。(また別で述べている通り、このフラグは残るべきだと思っています。)

2020-11-12 23:42 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> +	 * Looper#start() から Looper#stop() の間に呼ばれなければならない。
> どうにもイメージが伝わっていない気がするのですが、 start() と debugStart() はこのクラスにつけられた二つのスイッチのようなものになっていました。

テストが存在しないコードのイメージをこちらが想像できなかっただけですね。制限が増えたと言われても正直よくわかりません。

>  (たとえば serve でポーズボタンが押された時)、する側 (serve) は~

headless-driver が serve を意識しなければならない理由がわかりません。外部からは Runner クラスのみしか操作できないインタフェースとなっているので。これらの Looper に対する説明は headless-driver の開発者のために書いたコメントのつもりでした。

議論するつもりはないので過去のものを revert します。

2020-11-12 23:43 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> +	debugStep(ms: number): void {
一箇所こちらのメソッドのみ引数を受け取るように変更しています。

2020-11-12 23:50 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> -	 * game-driverがプレイを続行する状態になっているかどうか
revert 済みです。

2020-11-13 07:15 UTC, xnv commented on packages/headless-driver-runner/src/Looper.ts
> +	 * Looper#start() から Looper#stop() の間に呼ばれなければならない。
> 議論するつもりはないので

こうばっさりだと腰から砕けるような感じですが、一応わからないと仰る点について補足させてください。

> 制限が増えたと言われても正直よくわかりません。

`Looper#start() から Looper#stop() の間に呼ばれなければならない。` これが新たに生じた制限だと考えています。

> headless-driver が serve を意識しなければならない理由がわかりません。

いや……ええと……？　serve は headless-driver の `外部` の例にすぎませんし、何より「意識せねばならない」とは主張していないつもりです。逆です。「意識しなければならなくなっていて、意識させるべきでない」と述べています。

`外部からは Runner クラスのみしか操作できないインターフェース` であるのは承知しています。……もしかして `Runner` は、この制約 (`Looper#start() から Looper#stop() の間に呼ばれなければならない。`) を暗黙に満たしてくれるということなのでしょうか。もしそうなら私の発言は見当はずれなので一定撤回せねばなりません。しかしそうでないならば、結局この制約 は `外部` にまで影響するはずです (だから serve を例に挙げました)。

そして正直なところ、 `Runner` が暗黙にこの制約を満たすことはできなさそうに思います。 `Looper#start()`, `stop()` の呼び出し契機は、概念的には  `Runner` の預かり知るところではないはずだからです。

2020-11-13 08:26 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> +	 * Looper#start() から Looper#stop() の間に呼ばれなければならない。
なるほど、補足ありがとうございます。

> Looper#start() から Looper#stop() の間に呼ばれなければならない。 これが新たに生じた制限だと考えています。

繰り返しになってしまいますが、こちらは「もともとそのような制限を持っていた」と勘違いしたために上記のコメントを補足しました。(`debug` という名前からこちらが勝手に想像した仕様です)

> Runner が暗黙にこの制約を満たすことはできなさそうに思います。

という点に関してはよくわかりません。よくわからないため「このような仕様を満たして実装してください」という意味を込めて `Looper` の各メソッドにコメントを明記したつもりでした。そして、それを動作として保証するために Runner に関するテストを追加しました。(なので当然 `Looper` を `Runner` や `Platform` の外部から操作することがあれば前述の「暗黙の動作」は満たさなくなりうることになります)

>  Looper#start(), stop() の呼び出し契機は、概念的には Runner の預かり知るところではないはずだからです。

概念的なことはおっしゃるとおりだと思います。この件は「`Looper#debugStart()`, `Looper#debugStop()` という謎のメソッドがあるが、テストが無く期待動作がよくわからなかったため、こちらが想像する動作を仕様として付け加えたが、それは間違いであった (= 議論する必要がない)」というところに帰着するのかと思います。

2020-11-13 08:54 UTC, yu-ogi commented on packages/headless-driver-runner/src/Looper.ts
> +	 * Looper#start() から Looper#stop() の間に呼ばれなければならない。
あ、すいません。

> headless-driver が serve を意識しなければならない理由がわかりません。

というのは serve 側がどのようなシーケンス/インタフェースで headless-driver を操作しているかを把握していないということです。headless-driver の外部利用の例は現状テストでのみ保証されていて、その限りでは

> イメージはともかくとしても実際問題、debugStop() する時 (たとえば serve でポーズボタンが押された時)、する側 (serve) は~

という状況は起こり得ないかと思います。

2020-11-16 03:02 UTC, xnv approved these changes

2020-11-16 05:10 UTC, merged