use strict, headless-driver-runner-v1
akashic-games/headless-driver pull request #212
Opened 2020-12-03 10:03 UTC by kamakiri01

## このPullRequestが解決する内容

https://github.com/akashic-games/headless-driver/pull/208 の分割PRです。

`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。
PRの範囲からあふれる修正は次の課題とします。

2020-12-03 23:51 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +		const { loopMode, skipThreshold } = this.driver!.getLoopConfiguration();
`|| this.driver == null` のチェックを L71 に追加してこちらの `!` を削除してしまいたいです。

2020-12-03 23:51 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
>  				id: this.player ? this.player.id : undefined,
自分が生成している変数の型を `unknown` として扱っているのに違和感があります。この箇所はおそらく `g.Player#id` に `undefined` を代入してしまっているためにエラーとなっているように見えます。`id: this.player ? this.player.id : "dummy"` や `id: this.player ? this.player.id : Date.now() + ""` などダミーの値を与えることで回避できないでしょうか。

2020-12-03 23:51 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
> +			throw (new Error("Cannot call Platform#getPrimarySurface() before setRenderer"));
細かいですが `setRenderer` -> `setRendererRequirement` としておきたいです。

2020-12-04 08:07 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
> +			throw (new Error("Cannot call Platform#getPrimarySurface() before setRenderer"));
直します。

2020-12-04 08:07 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
>  				id: this.player ? this.player.id : undefined,
実は、L163 で `as RunnerPlayer` を付けたので、player変数は unknown型を渡さなくてもビルドを通すことができます。
unknownを付けたのは、L163で事後的に型が付くことを示せないかと思ったためですが、違和感あれば無くても構わないと思います。

2020-12-04 08:07 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +		const { loopMode, skipThreshold } = this.driver!.getLoopConfiguration();
削除します。ここで `!` を残したいモチベーションは無いです。

2020-12-06 23:57 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
>  				id: this.player ? this.player.id : undefined,
「ビルドを通す」よりも「型の食い違いを防ぐ」ことを主目的にしたいです。

2020-12-07 04:38 UTC, xnv requested changes

2020-12-07 04:38 UTC, xnv commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
>  	private eventHandler: pdi.PlatformEventHandler | null = null;
本題から離れそうですがこの表記するなら `prrimarySurface` やら `rendererReq` やらもここで `null` 代入しちゃいたくなりますね。

2020-12-07 04:38 UTC, xnv commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				player: player as RunnerPlayer,
- この型必要でしょうか。 `g.Player` があれば不要な気がしますが……。概念的にも、 `GameDriver` が規定しているはずの引数型をここで独自に定義しなければならないというのは直観的ではないように思えます。
- もしかすると、 `g.Player` が v1 系では strict でないなどで齟齬が出てしまうかもしれませんが、 `{ id: this.player.id! : undefined!, ... }` みたいに `!` にして、コメントで補足するとか方が意図が伝わりやすいかと思います。

2020-12-09 10:57 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				player: player as RunnerPlayer,
https://github.com/akashic-games/headless-driver/pull/212#discussion_r535731109 で指摘された箇所に繋がるのですが、  `"dummy"` を入れることで型を通そうと思います。
`undefined!` は外部に渡す型として考えると避けたほうが良さそうな気がしています。

2020-12-09 10:57 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
>  	private eventHandler: pdi.PlatformEventHandler | null = null;
確かに、こちらに揃えます。

2020-12-09 10:57 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
>  				id: this.player ? this.player.id : undefined,
別で議論して、従来 `undefined` を渡していた利用先に `"dummy"` を渡して良いのかという点について、利用先側がstrict有効な型に合わせるべき、ということになりました。
`"dummy` を渡すようにして型を一致させます。

2020-12-09 23:24 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
>  		this.loopers = [];
せっかくなのでこちらも揃えるべきかと。

2020-12-09 23:24 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				id: this.player ? this.player.id : "dummy",
すいません、自分でコメントしておいて恐縮ですが初期値が省略されたときの値が `dummy` というのは少し違和感があります。(利用者が明示的に「この値は仮ですよ」というニュアンスが強く、実際に与えられる暗黙の値としては少々不適切な気がしています)
`Date.now() + ""` でいかがでしょう。

2020-12-09 23:24 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				player: player,
こちらも不要な差分かと思います。

2020-12-10 04:54 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
>  		this.loopers = [];
定数で初期化できるところは揃えるようにします。

2020-12-10 04:54 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				player: player,
確かに、削除します。

2020-12-10 04:55 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				id: this.player ? this.player.id : "dummy",
この箇所、`"dummy"` にしますとコメント返事をしたあとで申し訳ないんですが、 `g.Player` は id が指定されないケースがある気がしています。（サーバインスタンスなど）
なので、 https://github.com/akashic-games/akashic-engine/blame/master/src/Player.ts を `id: string | undefined` に直して、ここは `undefined` を渡す挙動を維持する、でも良いのではないかと思っています。

その場合、ここでは `undefined!` を渡しておき、 `g.Player` の型に上記の修正が入ったら、適当なタイミングで `!` を外す、という流れで移行できると思いますが、どうでしょうか。

2020-12-10 05:19 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				id: this.player ? this.player.id : "dummy",
はい、その対応でも良いかと思います。[akashic-engine でもプレイヤーIDが省略されるケースが想定さている](https://github.com/akashic-games/akashic-engine/blob/0f91d7c00bc4cc95466047585f25e7915ae810b2/src/Game.ts#L332-L344) のが見受けられるので、むしろその方が自然かもしれません。
その場合わかりやすいように `TODO` や `undefined` または `@ts-ignore` をつけるような対応をお願いいただけないでしょうか。

2020-12-10 10:48 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +				id: this.player ? this.player.id : "dummy",
ありがとうございます。コメント付けて修正します。

2020-12-10 23:05 UTC, yu-ogi approved these changes

2020-12-14 10:16 UTC, xnv approved these changes

2020-12-17 04:37 UTC, merged