fix error
akashic-games/headless-driver pull request #220
Opened 2020-12-17 10:23 UTC by kamakiri01

https://github.com/akashic-games/headless-driver/runs/1568600096 ビルドエラーへの対応です。

2020-12-17 11:06 UTC, xnv commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +						game.external[key] = this.externalValue![key]!;
- V2 側同様、 `this.externalValue!` の `!` は不要ではありませんか。(if で guard されていそう)
- V3 側に同じ対応は不要でしょうか。
-

2020-12-17 11:13 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +						game.external[key] = this.externalValue![key]!;
なぜか手元では再現しませんが、 `externalValue` の `!` は不要なはずですが、 Actions によるビルドでは必要なようです（ https://github.com/akashic-games/headless-driver/pull/220/commits/011b124f88afc0013d7407f8023481333ad96055 との差分）

2020-12-18 02:51 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +						game.external[key] = this.externalValue![key]!;
念の為確認してみましたが、こちらの環境でもエラーとなったので GitHub Actions だけの問題ではなさそうです。

2020-12-18 04:33 UTC, kamakiri01 commented on packages/headless-driver-runner-v1/src/RunnerV1.ts
> +						game.external[key] = this.externalValue![key]!;
リポジトリの clone から新規に行うことで手元で再現しました。

2020-12-21 00:22 UTC, yu-ogi commented
さすがにこの修正に 8 コミットも必要はない (コミットメッセージも同じですし) と思うので Squash Merge かブランチを作り直すかの対応をお願いしたいです。

2020-12-21 02:44 UTC, xnv requested changes
PR 作り直すかはさておき内容は approved です。

2020-12-21 02:44 UTC, xnv approved these changes
(……失礼、なぜか approved といいながら request changes してしまった)

2020-12-21 02:48 UTC, yu-ogi approved these changes
同じく修正内容は approved です。

2020-12-21 06:49 UTC, kamakiri01 commented
Squash Mergeします。

2020-12-21 06:51 UTC, merged