Add akashic eslint config
akashic-games/headless-driver pull request #225
Opened 2021-01-26 05:34 UTC by ShinobuTakahashi

## 概要
- akashic/eslint-config の導入。
  - lint 対応 (eslint --fix による修正等)

**lint エラーが出ていますが、lintエラーは別途対応します。このPRはエラー修正後にマージします**

2021-03-26 04:37 UTC, ShinobuTakahashi commented on packages/headless-driver-runner-v3/src/__tests__/NodeCanvasGlyphFactory.spec.ts
> +			path.join(outputPath, "glyph_factory_test_01_jis_level_1_sans-serif.png")
` `` `  ->  `""` --fix により自動修正

2021-03-26 05:42 UTC, yu-ogi requested changes
eslint-config-prettier の対応をお願いします。 🙏

2021-03-26 05:42 UTC, yu-ogi commented on packages/headless-driver-runner-v1/package.json
> +    "lint": "eslint \"src/**/*.ts\" --fix"
prettier と eslint の --fix を併用すると部分的に競合してしまう (prettier または eslint の実行順により差分が出てしまう) ことがあります。[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) を利用して競合を回避していただけないでしょうか。
[akashic-engine](https://github.com/akashic-games/akashic-engine/blob/d5c298f1fa76832674dd98ef80bb6144b578deef/.eslintrc#L4) が参考になるかと思います。

2021-03-26 05:42 UTC, yu-ogi commented on packages/headless-driver-runner-v1/src/platform/NullRenderer.ts
> +// NullRenderer class は定義のみあれば良いので、no-unused-vars を無効とする。
こちらって必要でしょうか。少なくとも [NullSurface](https://github.com/akashic-games/headless-driver/blob/1695f7578a333b7954df5f702ebe1cf783ea9686/packages/headless-driver-runner-v1/src/platform/NullSurface.ts#L10) から参照されていますし、実際に利用されているのでコメント内容も不適切な気がします。

2021-03-26 05:42 UTC, yu-ogi commented on packages/headless-driver-runner-v3/src/platform/graphics/null/NullRenderer.ts
>  		return null!; // TODO: pdi-types 側の型を修正
別件ですがこちら既に `!` 外せないでしょうか。

2021-03-26 07:36 UTC, ShinobuTakahashi commented on packages/headless-driver-runner-v1/package.json
> +    "lint": "eslint \"src/**/*.ts\" --fix"
なるほど、ありがとうございます。
`eslint-config-prettier` 追加しました。

2021-03-26 07:36 UTC, ShinobuTakahashi commented on packages/headless-driver-runner-v1/src/platform/NullRenderer.ts
> +// NullRenderer class は定義のみあれば良いので、no-unused-vars を無効とする。
すいません、v3だけ修正して v1, v2 そのままでした。修正しました。

2021-03-26 07:36 UTC, ShinobuTakahashi commented on packages/headless-driver-runner-v3/src/platform/graphics/null/NullRenderer.ts
>  		return null!; // TODO: pdi-types 側の型を修正
pdi-types の Renderer#_getImageData() の戻り型が  `ImageData | null` になっていましたので、こちらも戻り型を修正し、`!` を外す修正を行いました。

2021-03-26 07:57 UTC, yu-ogi approved these changes

2021-03-26 07:57 UTC, yu-ogi commented on packages/headless-driver-runner-v2/src/platform/NullRenderer.ts
> +// NullRenderer class は定義のみあれば良いので、no-unused-vars を無効とする。
こちらも削除お願いします。

2021-03-31 03:50 UTC, kamakiri01 approved these changes

2021-03-31 09:35 UTC, merged