replace AmflowStore to interface
akashic-games/headless-driver pull request #263
Opened 2021-06-09 11:30 UTC by kamakiri01

## このpull requestが解決する内容

### 概要

`AmflowStore` を interface にし、既存の `AmflowStore` 実装を `MemoryAMFlowStore` にリネームします。
また、 `AMFlowClientManager#createAMFlowStore` で生成していた `AmflowStore` をやめ、外部から factory を渡せるように変更します。
## 破壊的な変更を含んでいるか?

- あり

2021-06-09 12:02 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +	onPutStartPointTrigger: Trigger<number> = new Trigger();
プレイ中一意な識別子として `frame: number` を使う想定です。

2021-06-14 07:21 UTC, xnv commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +	onPutStartPointTrigger: Trigger<number> = new Trigger();
周囲に合わせるなら `putStartPointTrigger` かと思います。逆にここで初めて公開する名前なので、ここで `onSendTick`, `onPutStartPoint` などと改名してしまってもよさそうです。(`〜Trigger` は初期の pdi-browser に合わせたもの、 `on〜` は AEv3 に合わせたもの、 `on〜Trigger` は前例がない認識)

2021-06-14 07:25 UTC, xnv commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +	onPutStartPointTrigger: Trigger<number> = new Trigger();
細かい情報は個別に GET する API を作って問い合わせればいいので、さほど慎重にならなくてよさそうです。ただまあ `{ frame, timeStamp }` ぐらい送ってもいいかなと思います。(手動ティックだと frame がほとんど情報にならないので)　オブジェクトにしておけば後でプロパティが増えても影響が小さいというのもあり。

2021-06-17 05:20 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +	onPutStartPointTrigger: Trigger<number> = new Trigger();
```
interface StartPointHeader {
	frame: number;
	timestamp: number;
}
```
を型定義してこれを送るようにします。

2021-06-17 05:21 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +	onPutStartPointTrigger: Trigger<number> = new Trigger();
確かに、`on~` に揃えます。

2021-06-17 06:48 UTC, yu-ogi commented on packages/headless-driver/src/play/AMFlowClientManager.ts
> +			store = this.factory(playId);
どうせ破壊的変更になるならば `AMFlowClientManager#createAMFlow(param: CreateAMFlowParameters)` のように引数を変更してしまったほうが良いのではないかと思います。
現状の変更だと `PlayManager` のコンストラクタまでも「`AMFlowStore` を生成する関数」を渡さなければならないのがどうにも直感に反しているようで気になっています。

2021-06-17 06:48 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
このPullRequestの意図をよくわかっていないのでそもそも論になってしまいそうですが headless-driver 
`AMFlowStore` は「headless-driver 内の AMFlowClient 実装の一部」に過ぎないもので、それを外部から渡さなければならない状況というのがよくわかっていません。
単に `AMFlowClient#store` を public にすればそれで良かったりはしないのでしょうか。

2021-06-17 09:10 UTC, kamakiri01 commented on packages/headless-driver/src/play/AMFlowClientManager.ts
> +			store = this.factory(playId);
確かに `PlayManager` 自体が factory を使うわけではないので、コンストラクタ経由で factory を渡すのは収まりが悪い気はします。
 `new AMFlowClientManager` が `PlayManager` の中にあるのでこうしていますが、コンストラクタ経由ではなく `PlayManager#createAMFlow` などにファクトリを渡すようにすべき、ということであっているでしょうか。
（コメントの意図を読み取れていなかったらすみません）

2021-06-17 09:11 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface StartPointHeader {
修正の意図とか共有せずにレビュー投げてしまって申し訳なんですが、以下の理由で `StartPoint ` よりも軽量なインターフェイスを定義したい、という経緯です。

- （ akashic serve の）サーバインスタンスで スナップショットが生成されたとき、パッシブインスタンスを実行している各インスタンスのクライアントにスナップショットが生成されたことを通知したい
- `StartPoint` は data にプレイログ本体を含むため、データサイズが不定で大きくなりうる。そのため、可能ならクライアントへは必要な情報だけを送りたい
- data を省いた `StartPoint` のサブセットを送る

…今思いましたが、この `StartPointHeader ` は headless-driver 以外でも利用されうるので、 @akashic/amflow 側で定義すべきかもしれません。

2021-06-17 09:11 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
https://github.com/akashic-games/headless-driver/pull/263#discussion_r653378844
の続きになってしまうのですが、 スナップショットがされたことを知るためには、 `AMFlow#onPutStartpoint` にハンドラを付ける必要があります。ただし、 `AMFlowClient(#store)` と `AMFlowStore` は現状 akashic serve から見えないところで生成されるため、いずれかを外部から見えるようにする必要がありました。

- `AMFlowStore` はプレイに対して必ず1つあるので、スナップショット生成をハンドルするなら `AMFlow#onPutStartpoint` を直接扱いたい
- @akashic/amflow の `PlayManager ` から `AMFlowStore` を辿る手もあるが、 `AMFlowStore` を serve から扱えるようにしたほうが確実
- （付属効果として）オンメモリ実装でない任意の playlog 保持機能を差し込めるようにもなる

そのため、headless-driver は  `MemoryAMFlowStore` 実装を export し、serve のファクトリがこれを生成する、という処理に切り替えたいと思っています。

2021-06-21 00:37 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface StartPointHeader {
`AMFlowStore !== AMFlow` なのでこの箇所のインタフェースとクライアントへのデータサイズは関係無いような?
データサイズ云々のロジックは headless-driver ではなく利用側 (serve など) で持つべきかと思います。

2021-06-21 01:02 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
前提として headless-driver の利用先は serve だけではないのですが、その全てが (headless-driver が export するとはいえ) `MemoryAMFlowStore` 実装を挿入しなければならないのは少々過激な対応に思えます。また同一の PlayID に別のインスタンスの `MemoryAMFlowStore` を渡したときの動作はどのようになるのでしょうか。利用側が常に「`PlayID` と `MemoryAMFlowStore` の紐付け」のロジックを持つ必要性が出てしまわないでしょうか。

> スナップショットがされたことを知るためには、 AMFlow#onPutStartpoint にハンドラを付ける必要があります。ただし、 AMFlowClient(#store) と AMFlowStore は現状 akashic serve から見えないところで生成されるため、いずれかを外部から見えるようにする必要がありました。

はい、なので

```typescript
...

const amflow = playManager.createAMFlow(playId0);
amflow.store.onPutStartPoint.add(...); // 生成直後に AMFlow#putStartPoint() をハンドリング
```

とするだけで解決しないのかな、と思った次第です。

2021-06-21 06:30 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
もう少し汎用的にするなら `onPutStartPoint` だけではなく `AMFlow` の各メソッドの発火トリガーを`AMFlowClient` に持たせてしまうのもありかもしれません。

```typescript
const amflow = playManager.createAMFlow(playId0);
amflow.onOpen.add(...); // AMFlow#open()
amflow.onAuthenticate.add(...); // AMFlow#authenticate()
amflow.onPutStartPoint.add(...); // AMFlow#putStartPoint()
...
```

2021-06-21 10:38 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface StartPointHeader {
> データサイズ云々のロジックは headless-driver ではなく利用側 (serve など) で持つべきかと思います。

`AMFlowStore !== AMFlow` 言及の意図が上手く読み取れていないかもしれないのですが、その場合の実装は、
```
import { ..., StartPoint } from "@akashic/amflow";
AMFlowStore#onPutStartPoint: Trigger<StartPoint>;
```

のようにして `StartPoint` を全部ハンドラに渡し、ハンドラの利用側 `data` を落とすなりするほうが良い、ということであっているでしょうか。

2021-06-21 10:39 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
> 同一の PlayID に別のインスタンスの MemoryAMFlowStore を渡したときの動作はどのようになるのでしょうか

同一のPlayIDに対して別インスタンスの `MemoryAMFlowStore` は「渡すべきではない」になると思います。
PlayIDに対して既存の `AMFlowStore` があるかどうかは、ファクトリを呼ぶ前に `AMFlowClientManager` が自身の `storeMap` から判定します。なので、別インスタンスの `MemoryAMFlowStore` を渡すケースは、ファクトリを意図的に `AMFlowStore` を再利用するよう実装しない限り発生しないと思います。

> とするだけで解決しないのかな、と思った次第です

はい、 `AMFlowClient#store` を public にすれば確かに `onPutStartPoint` をハンドリングできるようになるのですが、以下の点で public にしませんでした。
 `AMFlowStore` は PlayID に対して1つですが、 `AMFlowClient` はプレイに紐づいたインスタンスの数だけ作られます。そのため、 `createAMFlow()` の生成タイミングで `onPutStartPoint` をハンドリングすると、インスタンスの数だけハンドラが付きます。
`PlayManager` まで `AMFlowStore` を公開すれば多重ハンドリングは避けられそうですが、そこまで辿るよりは `AMFlowStore` を直接参照できるようにするほうが妥当な気がしています。

2021-06-22 00:21 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface StartPointHeader {
> AMFlowStore !== AMFlow 言及の意図が上手く読み取れていない

https://github.com/akashic-games/headless-driver/pull/263#discussion_r653378844 のコメントの二番目の

> StartPoint は data にプレイログ本体を含むため、データサイズが不定で大きくなりうる。そのため、可能ならクライアントへは必要な情報だけを送りたい

への返答になります。`AMFlowStore` に「クライアント」という概念は今のところ存在していません。

実装をどうすべきかはこのモジュールのAPIの責務範囲外なので言及できませんが、少なくとも `onPutStartPoint` というトリガー名で `StartPoint` が情報として渡ってこないのが奇妙に思います。

2021-06-22 00:35 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
同一PlayIDの件はおっしゃるとおりでしたね。失礼しました。

> AMFlowStore は PlayID に対して1つですが、 AMFlowClient はプレイに紐づいたインスタンスの数だけ作られます。そのため、 createAMFlow() の生成タイミングで onPutStartPoint をハンドリングすると、インスタンスの数だけハンドラが付きます。

ここの `そのため` の論理展開がよくわからないのですが [writeTick 権限を持つインスタンス](https://github.com/akashic-games/amflow/blob/54eb3c57e0c7552ff70fc4003bc0814568821f4c/src/Permission.ts#L15) にのみハンドラを登録すればよいのではないのでしょうか。serve を含め大部分のケースでは一つのプレイに一つのみ存在するかと思います。

全体的に「serve でこのように実装したいからそれに合わせて headless-driver を修正している」というような印象を受けます。先にも書きましたが headless-driver は serve 以外でも利用されているものなので疎な関係を維持しておきたいです。

2021-06-22 05:43 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
別で議論しましたが（不足した経緯あれば追記お願いします）、  `interface AMFlowStore` は現状 `AMFlowClient` の内部実装として実装された状態であり、 export するのであれば I/F を整理した後にしたい、という状況があります。そのため、 `AMFlowStore` の export はこのPRでは対応しません。

元々 `AMFlowStore` を外から参照できるようにしたいのは、各プレイに対して `AMFlowClient` は（アクティブ・パッシブ問わず）複数生成されるが、 `AMFlowStore` は一意であるためでした。 `AMFlowClient` に `onPutStartpoint` トリガーを追加した場合、別の `AMFlowClient` から同じ `AMFlowStore` への `putStartPoint` を拾うことが出来ませんでした。

また、 `AMFlowStore` のファクトリを与えるようにする実装は、外部から `AMFlowStore` 実装をわたせるようにすることで、より汎用性を持つことを狙うという（このPRからやや踏み出した）意図がありました。ですが、上述の I/F 整理の前に行うことは性急であるため、これは今後の検討とします。

writeTick 権限を持つインスタンスは、 serve 側で `RunnerManager#createRunner()` の中で対応をします。

本PRは、現状を踏まえた対応として、 `AMFlowClient#onCallPutStartPoint` を追加し、 `AMFlowClient` から `putStartPoint` が呼ばれた際に発火するようにします。 serve ではこれを利用し、アクティブインスタンスの `putStartPoint` 通知を取得できるようにします。

2021-06-22 06:22 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
> 本PRは、現状を踏まえた対応として、 AMFlowClient#onCallPutStartPoint を追加し、 AMFlowClient から putStartPoint が呼ばれた際に発火するようにします。 serve ではこれを利用し、アクティブインスタンスの putStartPoint 通知を取得できるようにします。

* `AMFlowStore#putStartPointTrigger` (既存の命名に合わせると) を新設してこれを `AMFlowStore#putStartPoint()` の呼び出し時に発火させる
* `AMFlowClient` 内で `AMFlowClient#onCallPutStartPoint` を発火させる処理を `AMFlowStore#putStartPointTrigger` にハンドルさせる

という方法であれば複数 AMFlow の懸念は無くなるのかな、とふと思いました。
(その場合トリガー名は `AMFlowClient#onSaveStartPoint` とか `AMFlowClient#onPutStartPoint` のほうが良さそう?)

2021-06-22 08:44 UTC, yu-ogi commented on packages/headless-driver/src/play/AMFlowClientManager.ts
> +			store = this.factory(playId);
はい、そのような意図でしたが本質的には `PlayManager#createPlay()` あたりから渡せるべき (一つのプレイに一つの存在なのでプレイを作る際に指定するのが筋) ですが、今回の修正とは無関係そうですね。

2021-06-22 11:17 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
そうですね、書いていただいたように `AMFlowStore#putStartPointTrigger` を追加して `AMFlowClient` で発火を受け取れば、「 `AMFlowClient` は自分に紐づいた `AMFlowStore` の putStartPoint すべてを検知する」ことができそうです。

2021-06-23 09:22 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +export interface AMFlowStore {
> export するのであれば I/F を整理した後にしたい

`export  class AMFlowStore` 自体は既にされていて、それを `AMFlowClient` に渡して利用する手立てがない、が現状説明としては正しそうですね 📝

2021-06-24 05:30 UTC, yu-ogi requested changes
通常の使い方だと利用されることがないので、できれば以下辺りで簡単なテストを追加しておきたいです。

https://github.com/akashic-games/headless-driver/blob/aa1f46b27a53cbae423c74cf57d9cb42b1af4c43/packages/headless-driver/src/__tests__/play.spec.ts#L443-L461

イメージ:

```typescript
let startPoint;
activeAMFlow.onPutStartPoint.add((s) => { startPoint = s; });

// Play を resume した後に putStartPoint できる 
activeAMFlow.putStartPoint(
...
 	(e) => { 
 		if (e) { 
 			reject(e); 
 			return; 
 		} 
		expect(startPoint).toEqual(...);
 		resolve(); 
 	} 

```

2021-06-24 12:18 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +		this.store.putStartPointTrigger.add((startPoint) => {
`destroy` されたら `remove` する処理は追加したほうが良いですね。追加します。
`AMFlowClient#onPutStartPoint` は Trigger の名前にもなるので、悩ましいところですが、 `_onPutStartPoint` か `onPutStartPointReceived` などを考えようと思います。

2021-06-28 00:03 UTC, yu-ogi reviewed
PullRequest のタイトルと説明を修正内容に合わせてください。

2021-06-28 00:03 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +	private _onPutStartPoint(startPoint: StartPoint): void {
既存のメソッド名に合わせて `onStartPointPut()` としてください。

2021-06-28 04:18 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +		this.store.putStartPointTrigger.add((startPoint) => {
あ、失礼しました。https://github.com/akashic-games/headless-driver/pull/263#discussion_r659395600 にもコメントしましたが他と合わせると `AMFlowClient#onPutStartPoint` が良さそうです。

2021-06-28 05:01 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +	private _onPutStartPoint(startPoint: StartPoint): void {
別で議論しましたが、 `private` なので互換を考慮しなくて良いこと、新しい実装では `Handler` 命名を利用していることから、 `putStartPointHandler()` とし、既存メソッドの名前も揃えます。

2021-06-28 05:01 UTC, kamakiri01 commented on packages/headless-driver/src/__tests__/play.spec.ts
> +					// putStartPoint した後に onPutStartPoint を発火する
はい、テストを主体として考えると `onPutStartPoint` を発火するのはテスト自身ではなく内部実装ですね。 
文章を直すと、「onPutStartPoint **が** 発火する」などが妥当でしょうか。

2021-06-28 05:20 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
>  		this.store = null!;
この辺りで `this.onPutStartPoint = null!;` をしておきたいです。

2021-06-28 05:20 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +	private sendTickHandler(tick: Tick): void {
議論した内容としては `handle...` (ここでは `handleSendTick()`) かと思います。

2021-06-28 05:20 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +		this.putStartPointTrigger.fire(startPoint);
こちらも `destroy()` 時に `null!` を代入しておきたいです。

2021-06-28 05:20 UTC, yu-ogi commented on packages/headless-driver/src/__tests__/play.spec.ts
> +					// putStartPoint した後に onPutStartPoint を発火する
まあテストコード見たままのコメントなので無くても問題ないかなと思います。

2021-06-28 05:37 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +	private sendTickHandler(tick: Tick): void {
お…っと、 `handle...` でした。直します。

2021-06-28 05:37 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
>  		this.store = null!;
追加します。

2021-06-28 05:37 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowStore.ts
> +		this.putStartPointTrigger.fire(startPoint);
こちらも追加します。

2021-06-28 05:45 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +			this.onPutStartPoint = null!;
細かいですが `this.store` の状態と `this.onPutStartPoint` の関係は独立なのでこの if の範囲外においておきたいです。

2021-06-28 06:38 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +			this.onPutStartPoint = null!;
修正します。

2021-06-28 07:16 UTC, yu-ogi reviewed
* 機能追加なのでマイナーバージョンの更新でお願いします。
* PullRequestの説明にある
> AMFlowStore#putStartPoint Trigger を追加し、これを基点に発火する AMFlowStore#onPutStartPoint を追加します。

はそれぞれ
* `AMFlowStore#putStartPointTrigger`
* `AMFlowClient#onPutStartPoint`

が正しいかと思います。

2021-06-28 07:16 UTC, yu-ogi commented on packages/headless-driver/package.json
> +    "@types/pngjs": "^6.0.0",
(念の為) renovate で `^` が消されるかと思います。

2021-06-28 07:16 UTC, yu-ogi commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +		this.store.putStartPointTrigger.add(this.handlePutStartPoint, this);
都度都度のコメントになってしまって恐縮ですがこちらは他と合わせて `AMFlowClient#open()` 内でハンドルしておきたいです。

2021-06-28 07:54 UTC, kamakiri01 commented on packages/headless-driver/src/play/amflow/AMFlowClient.ts
> +		this.store.putStartPointTrigger.add(this.handlePutStartPoint, this);
ハンドル位置直します。

（元々 `AMFlowClient#open()` が複数回呼ばれるケースに対応した措置でしたが、ユーザ側（今は serve ）で `isActive` 判定を入れたので `open` タイミングでも問題無くなっていました）

2021-06-28 08:00 UTC, yu-ogi approved these changes
LGTM です。ご対応ありがとうございます。

2021-06-28 08:02 UTC, kamakiri01 commented on packages/headless-driver/package.json
> +    "@types/pngjs": "^6.0.0",
固定します。

2021-06-30 07:11 UTC, xnv approved these changes

2021-07-01 05:34 UTC, merged