Add _stepLoopers() to Runner
akashic-games/headless-driver pull request #271
Opened 2021-08-03 04:44 UTC by ShinobuTakahashi

## 概要

V3 のみ Looper に NaN を渡せるようにするため、Runner に  `stepLoopers()` を追加します。
v1, v2 では `stepLoopers()` はサポートしません。

2021-08-03 05:32 UTC, yu-ogi requested changes
悩ましいのですがラベルは bug が適切かと思います。

2021-08-03 05:32 UTC, yu-ogi commented on packages/headless-driver-runner/src/Runner.ts
> -					this._stepHalf();
ここの差分は必要ないかと思います。理由は以下の2点です。
* この箇所で 1/2 のフレームだけ進むというのは実装上大きな問題ではない
* この分岐ロジックを呼び出し側で持つのは奇妙で、将来的に負債となりえる

`RunnerV3#step()` (以下のL67) の部分だけの修正で十分かと思います。
https://github.com/akashic-games/headless-driver/blob/d9f64fb6abb2d8257764c8d33c21aff67416a96f/packages/headless-driver-runner-v3/src/RunnerV3.ts#L57-L68

2021-08-03 05:32 UTC, yu-ogi commented on packages/headless-driver-runner-v3/src/RunnerV3.ts
> +	protected _stepLoopers(): void {
このあたりの差分 (`_stepLoopers()` の追加) も必要ないかと思います。理由は上記コメント同様です。

2021-08-03 05:43 UTC, xnv commented on packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
> +			this.loopers[i].debugStep(NaN);
同意ですが「1フレームだけ」よりも「次のフレームまで」としたいです。(前者は、現在の状況に関わらず「1フレーム時間 (60fps なら 16.666ms) 進める」ようにも読めますが、実装は後者に寄せたはずでしたよね)

2021-08-03 05:52 UTC, xnv commented on packages/headless-driver-runner/src/Runner.ts
> -					this._stepHalf();
「この部分で分岐すべきでない」に同意です。

ただ、せっかく厳密に 1 ステップ進める機能があるならここでもそれを使いたいのも確かに思えます。(少なくともすぐ上のコメントは嘘になりますし)　以下のような方針でどうでしょうか。

- `_stepHalf()` を `_stepMinimal()` に改名し、「次フレームを飛ばさない程度の時間進む」メソッドとする
- v3 系の `_stepMinimal()` は単に  `step()` を呼び出す
- v2, v1 系の `_stepMinimal()` に、現状ここにあるコメント (「厳密な 1 フレームの更新ができない」) を移動する

(`_stepMinimal()` というより `_advanceUnit()` とかの方が適切な名前かもしれませんが、詳細はさておき)

2021-08-03 06:46 UTC, ShinobuTakahashi commented on packages/headless-driver/src/__tests__/runner.spec.ts
> +		const engineFilesToPath = path.join(__dirname, "tmp", "engineFilesV3_0_19.debug.js");
テストで使用していた engineFiles が最新のgameDriverを取り込んだものではなかったため、最新の 3.0.19 へファイルごと置き換えました。

2021-08-03 06:46 UTC, ShinobuTakahashi commented on packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
> +			this.loopers[i].debugStep(NaN);
ありがとうございます。コメント修正しました。

2021-08-03 07:03 UTC, ShinobuTakahashi commented on packages/headless-driver-runner-v3/src/RunnerV3.ts
> +	protected _stepLoopers(): void {
`Runner#_stepLoopers()` 削除しました。

2021-08-03 07:03 UTC, ShinobuTakahashi commented on packages/headless-driver-runner/src/Runner.ts
> -					this._stepHalf();
ありがとうございます。`Runner#_stepHalf()` -> `_stepMinimal()` へ修正し、v1,　v2 の方はコメントを追加するよう修正しました。

2021-08-04 03:18 UTC, yu-ogi approved these changes

2021-08-04 03:34 UTC, xnv approved these changes

2021-08-04 03:50 UTC, merged